import type { Metadata } from "next";
import "@/src/components/globals.css";
import AppRoot from "../components/root/app";

export const metadata: Metadata = {
  title: "ASKP",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <AppRoot>{children}</AppRoot>;
}
