import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "src/components/globals.css";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";
import { BackAPIClient as api } from "@/src/bClient/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ASKP",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const communities = await (await api()).communitiesAll();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header communities={communities} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
